### ISSUE TITLE
안녕하세요 kr-custom-tts로 학습을 시키려고 공부하다가 이슈가 생겨 글 남깁니다. 

### ISSUE THREAD

**Issue by doh0106** [seastar105/kr-custom-tts#2]
올려주신 코드를 감사하게 쓰고 있습니다. 그런데 23/05/15 기준으로 코랩으로 돌리면 맞지 않는 것들이 있는 것 같아서 글을 남깁니다. 코랩에서는 넘파이 버전이 맞지 않아서 numpy를 1.24로 따로 설치해서 바꿔야 할 것 같습니다. 그리고 espnet의 레포에서 tools에서 kaldi 폴더가 사라져서  /content/espnet/tools에 kaldir를 깃클론 해주어야 돌아가는 것 같습니다.  바꾼 노트북 파일을 메일로 보내보겠습니다. 감사합니다.

**Comment by seastar105** [comment]
@doh0106 이슈 제보 감사합니다. espnet 쪽의 설치 쪽 업데이트가 꽤 많이 있네요. 체크에 시간이 걸릴 거 같아 주말에 한 번 보겠습니다.

**Comment by seastar105** [comment]
@doh0106 말씀주신대로 numpy 버전과 kaldi 폴더 클론하는 부분을 수정하니 학습이 진행되는 것을 확인했습니다. 감사합니다.
