### ISSUE TITLE
필요한 패키지 버전과 샘플과 같이 아웃풋이 나오기 위해 학습한 분량이 어느 정도인지 궁금합니다!

### ISSUE THREAD

**Issue by Foreist** [seastar105/kr-custom-tts#3]
espnet version 관련 이슈가 있는 것 같아서, espnet 사용하셨던 버전이랑 샘플처럼 아웃풋이 나오기 위해 학습했던 분량은 어느 정도인지 궁금합니다!

**Comment by seastar105** [comment]
@Foreist JETS 모델이 추가된 릴리즈를 사용했던걸로 기억합니다. 202205 릴리즈 혹은 202207 릴리즈를 사용해주시면 될 거 같습니다. colab 노트북을 만들 당시에는 colab 환경 때문에 토치 버전을 1.10을 사용했는데 1.13.1도 괜찮은지 확인중입니다.

사용했던 데이터는 https://github.com/seastar105/kr-custom-tts/blob/main/tts1/org/transcripts.txt 의 문장들을 제가 직접 녹음했으며 3400초 분량입니다. 음성 분량에 따른 퀄리티 차이는 실험해보지 않은 상태입니다.
